# Generated by Django 3.2.2 on 2022-12-21 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mismatch', '0002_user_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date',
        ),
    ]
