# Generated by Django 3.2.2 on 2023-01-14 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mismatch', '0005_category_response_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='category_id',
            new_name='category',
        ),
    ]
