# Generated by Django 3.2.2 on 2023-01-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mismatch', '0006_auto_20230114_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.IntegerField(),
        ),
    ]
