# Generated by Django 3.2.2 on 2023-01-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mismatch', '0007_alter_response_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response',
            field=models.IntegerField(null=True),
        ),
    ]
